#  docker run -d --name test_db_2 -p 5432:5432 -e POSTGRES_PASSWORD=pass -e POSTGRES_DB=test_db postgres:12.3-alpine
#  docker stop test_db_2
#  docker start test_db_2
version: '3.1'
services:
  db:
    image: postgres:12.3-alpine
    #    container_name: test_db
    restart: always
    environment:
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
  app:
    build:
      dockerfile: Dockerfile
      context: ./
    #    container_name: <container_name>
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - 3000:8080
    links:
      - db
